# Theme settings
doks:
    baseurl:
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: Python for Atmosphere and Ocean Science
            image:
        nav:
            - item_name: Getting Started
              item_url: '/start'
            - item_name: PyAOS Stack
              item_url: '/stack'
            - item_name: Package Index
              item_url: '/packages'
            - item_name: Training
              item_url: '/training'
    footer:
        content:
            logo:
                text: Python for Atmosphere and Ocean Science
                image:
            copyright:
        social_list:
            - network_name: github
              profile_url: 'https://github.com/PyAOS'
            - network_name: twitter
              profile_url: 'https://twitter.com/hashtag/PyAOS'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
